#define frosted_glass 2
#define normal_glass 1
name=Grafun
version=1.0
author=Gra
description=My first shader pack
profile.compatibility=true
dhShadow.enabled=true
texture.composite.colortex14=image/Milkway.png
uniform.vec3.sun_origin_base_color= vec3(1.0,1.0,1.0)
uniform.float.glass=1.5
uniform.float.sun_atten_g=0.85
uniform.float.sun_atten_b=0.72
uniform.vec3.light_pollution_color= vec3(1.0,1.0,1.0)