#define frosted_glass 2
#define normal_glass 1
name=Grafun
version=1.0
author=Gra
description=My first shader pack
profile.compatibility=true
dhShadow.enabled=true
customTexture.starmap=image/Milkway.png
customTexture.starlightmap=image/Milkway_skylight.png
uniform.vec3.sun_origin_base_color= vec3(1.0,1.0,1.0)
uniform.float.glass=1.5
uniform.float.sun_atten_r=0.955
uniform.float.sun_atten_g=0.897
uniform.float.sun_atten_b=0.768
uniform.vec3.light_pollution_color= vec3(1.0,1.0,1.0)
screen= [Sky] [Camera] [Render]

screen.Sky= Realtime_Sky Side_Scatter
screen.Camera=[Exposure] [Vignette]  [Bloom]  
screen.Exposure= Auto_Expousre Auto_Expousre_Mode <empty> <empty> <empty> <empty><empty><empty> Expousre_Gain
moon=false
shadowRenderSky=true
blend.gbuffers_water.colortex3 = DST_COLOR ZERO ONE ONE
screen.Bloom=Bloom Bloom_Scatter Sun_Bloom 
sliders = Bloom_Scatter Expousre_Gain 
screen.Vignette=Vignette Vignette_Type

screen.Render=Realtime_Skylight Realtime_Sunlight 